### ISSUE TITLE
[Question] Celery和Core的Pod使用相同的Label

### ISSUE THREAD

**Issue by Komey** [jumpserver/helm-charts#120]
**请描述您的问题.**
Chart里Celery使用了和Core相同的Pod.metadata.labels
https://github.com/jumpserver/helm-charts/blob/main/charts/jumpserver/templates/celery/deployment-celery.yaml#L25

同时Core的Service也是用的这部分Labels
https://github.com/jumpserver/helm-charts/blob/main/charts/jumpserver/templates/core/service-core.yaml#L31

这样的配置方法是有特殊用途吗？

**Comment by wojiushixiaobai** [comment]
没，你可以根据实际需求自行处理下。
