### ISSUE TITLE
[Question] jms-core 能否使用minio，不使用pvc

### ISSUE THREAD

**Issue by xiyuanpingtadi** [jumpserver/helm-charts#137]
k8s使用的 StorageClasses 是 vsphere-csi 不支持 ReadWriteMany ，导致无法安装 jms-core。
helm安装时能否让core不使用pvc，使用minio等对象存储来保存 jumpserver-data 和 jumpserver-log。

**Comment by wojiushixiaobai** [comment]
你创建 s3 的 storageclass 后，直接在 jumpserver 的 [values.yaml](https://github.com/jumpserver/helm-charts/blob/main/charts/jumpserver/values.yaml) 里面指定这个 SC 试试
