### ISSUE TITLE
[Question] microk8s 部署后websokcet一直提示无法连接

### ISSUE THREAD

**Issue by MarsMan1994** [jumpserver/helm-charts#138]
**请描述您的问题.**
使用microk8s部署jumpser后使用ingress暴露服务，域名访问web端是正常的，但是登录后websocket无法连接，按照网上文章修改ingress 后还是无法解决
下面是我的ingress
![图片](https://github.com/jumpserver/helm-charts/assets/32359814/ea9bb85c-6b82-4357-bddc-6528aa09275c)

**Comment by wojiushixiaobai** [comment]
values.yml 里面有 ingress 相关配置，直接开启即可

**Comment by MarsMan1994** [comment]
使用helm3 部署的jumpserver  websocket 还是异常 我的环境是 microk8s  v1.27.2    1.27/stable
根据日志判断是请求websocket 时 ingress  upgrade 失败。导致流量并没有转发到websocket的处理程序，所以返回404错误。
我用port forward 直接访问服务是正常的。
下面是helm自动部署生成的ingress 
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jumpserver-ingress
  namespace: jumpserver
  uid: 9952c44c-167c-400c-bda9-8620915eba96
  resourceVersion: '85259'
  generation: 1
  creationTimestamp: '2023-06-05T06:36:58Z'
  labels:
    app.kubernetes.io/instance: jumpserver
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jumpserver
    app.kubernetes.io/version: v3.3.1
    helm.sh/chart: jumpserver-3.3.1
  annotations:
    kubernetes.io/ingress.class: nginx
    meta.helm.sh/release-name: jumpserver
    meta.helm.sh/release-namespace: jumpserver
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Upgrade "websocket";
      proxy_set_header Connection "Upgrade";
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    nginx.ingress.kubernetes.io/proxy-body-size: 4096m
  managedFields:
    - manager: helm
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2023-06-05T06:36:58Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/ingress.class: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
            f:nginx.ingress.kubernetes.io/configuration-snippet: {}
            f:nginx.ingress.kubernetes.io/proxy-body-size: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          f:rules: {}
          f:tls: {}
  selfLink: >-
    /apis/networking.k8s.io/v1/namespaces/jumpserver/ingresses/jumpserver-ingress
status:
  loadBalancer: {}
spec:
  ingressClassName: public
  tls:
    - hosts:
        - jumpserver.tetest.pro
      secretName: jumpserver-xxx-pro-tls
  rules:
    - host: jumpserver.xxx.pro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jumpserver-jms-web
                port:
                  number: 80`
