### ISSUE TITLE
[Bug] 组件kael有配置项决定启用还是禁用，但禁用后，web启动不了

### ISSUE THREAD

**Issue by spbdev** [jumpserver/helm-charts#142]
**JumpServer 版本(v1.5.9以下不再支持)**
v3.5.2

**浏览器版本**
浏览器无关

**Bug 描述**
看文档介绍，kael是管理ChartGPT资源，因为没有这方面的需求，试着部署的时候将kael禁用掉(values.yaml当中，配置kael的enabled: false)，然后发现部署后唯独web所在pod启动失败，看错误信息，应该是找不到kael服务导致。既然允许配置，是不是不应该起不来啊？

**Bug 重现步骤(有截图更好)**
1.  在values.yaml中配置kael的enabled: false
2. 正常helm安装部署jumpserver
3. 观察pod状态，可见web组件启动不了

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/helm-charts/blob/main/charts/jumpserver/configs/jms-web/default.conf
忘记写判断了，下个版本我修复下。

**Comment by carllhw** [comment]
> * https://github.com/jumpserver/helm-charts/blob/main/charts/jumpserver/configs/jms-web/default.conf
>   忘记写判断了，下个版本我修复下。
> * [x]  [perf: 优化 web 组件配置文件](https://github.com/jumpserver/helm-charts/commit/d350aa74efe963cc9d3ee18794cf58883dcdfb42)
> 
> 大致将 `charts/jumpserver/configs/jms-web/default.conf` 里面的内容改为如下所示，然后 `upgrade` 下再试试看
> 
> ```yaml
> {{ $koko := printf "http://%s-%s:%s" (include "jumpserver.fullname" $) "jms-koko" ($.Values.koko.service.web.port | toString) }}
> {{ $lion := printf "http://%s-%s:%s" (include "jumpserver.fullname" $) "jms-lion" ($.Values.lion.service.web.port | toString) }}
> {{ $core := printf "http://%s-%s:%s" (include "jumpserver.fullname" $) "jms-core" ($.Values.core.service.web.port | toString) }}
> {{ $chen := printf "http://%s-%s:%s" (include "jumpserver.fullname" $) "jms-chen" ($.Values.chen.service.web.port | toString) }}
> {{ $kael := printf "http://%s-%s:%s" (include "jumpserver.fullname" $) "jms-kael" ($.Values.kael.service.web.port | toString) }}
> server {
>     listen {{ $.Values.web.service.web.port }};
>     server_name  _;
>     server_tokens off;
> 
>     client_max_body_size 4096m;  # 录像及文件上传大小限制
> 
>     location /ui/ {
>         try_files $uri / /index.html;
>         alias /opt/lina/;
>     }
>     location /luna/ {
>         try_files $uri / /index.html;
>         alias /opt/luna/;
>     }
>     location /download/ {
>         alias /opt/download/;
>     }
>     location /media/replay/ {
>         add_header Content-Encoding gzip;
>         root /opt/jumpserver/data/;
>     }
>     location /static/ {
>         root /opt/jumpserver/data/;
>     }
>     {{- if .Values.koko.enabled }}
>     location /koko/ {
>         proxy_pass {{ $koko }};
>         proxy_buffering off;
>         proxy_http_version 1.1;
>         proxy_request_buffering off;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_ignore_client_abort on;
>         proxy_connect_timeout 600;
>         proxy_send_timeout 600;
>         proxy_read_timeout 600;
>         send_timeout 6000;
>     }
>     {{- end }}
>     {{- if .Values.lion.enabled }}
>     location /lion/ {
>         proxy_pass {{ $lion }};
>         proxy_buffering off;
>         proxy_http_version 1.1;
>         proxy_request_buffering off;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection $http_connection;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_ignore_client_abort on;
>         proxy_connect_timeout 600;
>         proxy_send_timeout 600;
>         proxy_read_timeout 600;
>         send_timeout 6000;
>     }
>     {{- end }}
>     {{- if .Values.chen.enabled }}
>     location /chen/ {
>         proxy_pass {{ $chen }};
>         proxy_buffering off;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection $http_connection;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_ignore_client_abort on;
>         proxy_connect_timeout 600;
>         proxy_send_timeout 600;
>         proxy_read_timeout 600;
>         send_timeout 6000;
>     }
>     {{- end }}
>     {{- if .Values.kael.enabled }}}
>     location /kael/ {
>         proxy_pass {{ $kael }};
>         proxy_buffering off;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection $http_connection;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_ignore_client_abort on;
>         proxy_connect_timeout 600;
>         proxy_send_timeout 600;
>         proxy_read_timeout 600;
>         send_timeout 6000;
>     }
>     {{- end }}
>     {{ if .Values.core.enabled }}}
>     location /ws/ {
>         proxy_pass {{ $core }};
>         proxy_buffering off;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "upgrade";
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
>     location ~ ^/(core|api|media)/ {
>         proxy_pass {{ $core }};
>         proxy_buffering off;
>         proxy_set_header X-Real-IP $remote_addr;
>         proxy_set_header Host $host;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     }
>     {{- end }}
>     location / {
>         rewrite ^/(.*)$ /ui/$1 last;
>     }
> }
> ```

https://github.com/jumpserver/helm-charts/blob/36c22334db218784676129891e98e826b99895b4/charts/jumpserver/configs/jms-web/default.conf#L84
https://github.com/jumpserver/helm-charts/blob/36c22334db218784676129891e98e826b99895b4/charts/jumpserver/configs/jms-web/default.conf#L101

这两个地方是不是多了`}`

**Comment by wojiushixiaobai** [comment]
- fix: https://github.com/jumpserver/helm-charts/commit/39e3e2d524235fb9205e9c602f988a591233d898
