### ISSUE TITLE
[Question] helm 升级时 jms-init-db 报错 'acls_connectmethodacl' already exists

### ISSUE THREAD

**Issue by xiyuanpingtadi** [jumpserver/helm-charts#144]
helm upgrade 从3.4.1升级到3.4.3和3.6.1都失败。
job `jms-init-db` pods 返回：
`django.db.utils.OperationalError: (1050, "Table 'acls_connectmethodacl' already exists")`

**Comment by xiyuanpingtadi** [comment]
删除 `acls_connectmethodacl` 表后 `jms-init-db` 返回 :
`django.db.utils.OperationalError: (3780, "Referencing column 'user_id' and referenced column 'id' in foreign key constraint 'acls_connectmethodac_user_id_10422014_fk_users_use' are incompatible.")`

**Comment by wojiushixiaobai** [comment]
3780 应该是 `字符集和排序规则不对应`，你导出 `sql` 后 `grep` 校验下

**Comment by xiyuanpingtadi** [comment]
可以了

**Comment by dilinliu1116** [comment]
我从3.9.3升级到3.10也遇到了这个问题，请问大佬是怎么解决的？
