### ISSUE TITLE
[Bug] 从2.8.5升级至2.8.20时失败

### ISSUE THREAD

**Issue by jesse-zhangh** [jumpserver/helm-charts#145]
**JumpServer 版本(v1.5.9以下不再支持)**
当前版本 2.8.5
计划升级版本2.8.20

**浏览器版本**
Chrome Version 117.0.5938.92 (Official Build) (64-bit)

**Bug 描述**
helm 部署在k8s上
目前使用的values模板是2.8.5的
升级时改了tag为2.8.20
升级命令：helm upgrade jms-k8s jumpserver/jumpserver -f values.yaml  -n jumpserver
提示错误：
Error: UPGRADE FAILED: cannot patch "jms-k8s-jumpserver-jms-core" with kind Deployment: Deployment.apps "jms-k8s-jumpserver-jms-core" is invalid: spec.template.spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type

**Bug 重现步骤(有截图更好)**
1.  修改values文件（版本2.8.5）中image tag为2.8.5
2. 升级部署helm upgrade jms-k8s jumpserver/jumpserver -f values.yaml  -n jumpserver
3. 提示错误：Error: UPGRADE FAILED: cannot patch "jms-k8s-jumpserver-jms-core" with kind Deployment: Deployment.apps "jms-k8s-jumpserver-jms-core" is invalid: spec.template.spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type
4. 服务状态
![image](https://github.com/jumpserver/helm-charts/assets/87465352/65fc824d-e1e9-4e9e-a860-97a43530b34e)

**Comment by jesse-zhangh** [comment]
values文件，我使用原来2.8.5的模板是否有问题？

**Comment by wojiushixiaobai** [comment]
从你的截图来看，你用的并不是 v2 版本的模板，chen 和 kael 组件是 v3 才引入的。
你重新检查下代码，用 v2.8 的模板应该是没问题的

**Comment by jesse-zhangh** [comment]
@wojiushixiaobai 
感谢回复。
使用的就是v2.8.5的模板，是否与命令有关？
我的升级命令：helm upgrade jms-k8s jumpserver/jumpserver -f values.yaml -n jumpserver
搜索helm
ubuntu@k8s-master1:~$ helm search repo jumpserver/jumpserver
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
jumpserver/jumpserver   3.7.1           v3.7.1          A Helm chart for Deploying Jumpserver on Kubern...
ubuntu@k8s-master1:~$

这里是3.7.1 所以才有chen 和 kael 组件 ？

**Comment by wojiushixiaobai** [comment]
。。。。你还是使用本地文件吧，这样获取的模板是最新版本的

**Comment by jesse-zhangh** [comment]
全部删除，重新安装，也提示错误：
```
ubuntu@k8s-master1:~/app/jumpserver/helm_v2.28.5$ helm install jms-k8s jumpserver/jumpserver -f values.yaml -n jumpserver
Error: INSTALLATION FAILED: Deployment.apps "jms-k8s-jumpserver-jms-core" is invalid: spec.template.spec.containers[0].livenessProbe.httpGet: Forbidden: may not specify more than 1 handler type
```

**Comment by jesse-zhangh** [comment]
![image](https://github.com/jumpserver/helm-charts/assets/87465352/5cb3d902-bca7-4849-9937-4234a10872a3)
执行安装，默认就是3.7版本了

**Comment by jesse-zhangh** [comment]
解决了，是我的问题，应用的chart文件不对。
@wojiushixiaobai 感谢帮助。顺便请教一下，现在默认禁用了grep命令，请问怎么添加允许呢?

**Comment by jesse-zhangh** [comment]
使用本地chart helm文件部署和更新
`helm install jms-k8s helm-charts-jumpserver-2.28.7/charts/jumpserver -f helm_v2.28.5/values.yaml -n jumpserver
helm upgrade jms-k8s helm-charts-jumpserver-2.28.7/charts/jumpserver -f helm_v2.28.5/values.yaml -n jumpserver`
