### ISSUE TITLE
[Bug] 3.8.2升级到3.9.1失败，升级到3.9.0也不行，查看pod似乎是升级数据库失败

### ISSUE THREAD

**Issue by spbdev** [jumpserver/helm-charts#147]
**JumpServer 版本(v1.5.9以下不再支持)**
v3.8.2

**浏览器版本**
浏览器无关

**Bug 描述**
helm方式，从3.8.2升级到3.9.1失败，就很长时间才提示超时。查看pod有多个升级数据库的pod处于err状态。logs pod看不到日志，就提示exec错误。已经恢复回3.8.2了，没法截图了。顺便，values.yaml中的镜像我已经从core改成core-ce了，不是镜像拉取不了的问题；也不是我升级不对的问题，一路从3.1左右跟着升级到3.8.2的，就这次不行。

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
升级是由 job 完成，你看看 job 的相关日志。

**Comment by spbdev** [comment]
再试了一次，同样的问题，查看job也看不到有用的错误信息，只是提示：
`kubectl -n jumpserver logs job/jms-jumpserver-jms-init-db
Found 5 pods, using pod/jms-jumpserver-jms-init-db-5jgnj
exec /bin/bash: exec format error`
就这么点错误信息

**Comment by wojiushixiaobai** [comment]
你这个是下载错误架构的镜像了吧，请检查你的镜像源使用正确的架构

**Comment by spbdev** [comment]
> 你这个是下载错误架构的镜像了吧，请检查你的镜像源使用正确的架构

不应该啊，就是values.yaml文件修改一下版本号以及core镜像改为core-ce，拉取镜像架构不应该是是自动的吗？而且之前升级也都OK的啊（升级到3.7.x和3.8.2都这么操作的)，除非你们构建的镜像有问题。我用的服务器确实是ARM架构的。

**Comment by wojiushixiaobai** [comment]
手动运行容器看看，随便到容器里面执行一个 shell 看看能不能正常执行

**Comment by spbdev** [comment]
> 手动运行容器看看，随便到容器里面执行一个 shell 看看能不能正常执行

还真是镜像架构不对。core-ce是用的crictl手动拉取的，inspect检查确实是amd64的，而用ctr拉取就是arm的，第一次遇到。
