### ISSUE TITLE
[Bug] magnus默认端口映射问题

### ISSUE THREAD

**Issue by taoyang987** [jumpserver/helm-charts#149]
**JumpServer 版本(v1.5.9以下不再支持)**
3.10.3

**浏览器版本**

**Bug 描述**
在values.yaml配置了magnus service mysql端口号为32061
最后生成的yaml(我用的helm --dry-run)中,所有magnus Deployment中所有涉及mysql端口号都变成了32061,其他地方涉及到magnus mysql端口号的也都变成了32061,而.magnus容器的端口号本来是为33061.所以magnus组件就可用了.
![image](https://github.com/jumpserver/helm-charts/assets/872386/39fd04f1-3d4b-4f52-b449-c69423342561)
<img width="396" alt="image" src="https://github.com/jumpserver/helm-charts/assets/872386/f602da92-7e86-4a24-93ad-2fb3a7b008e0">

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
没太理解啥意思
