### ISSUE TITLE
[Bug] Failed to pull image "ghcr.io/jumpserver/core-ce:v3.10.10": Error response from daemon: manifest unknown

### ISSUE THREAD

**Issue by aledr** [jumpserver/helm-charts#152]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**
<html>
<body>

Failed to pull image "ghcr.io/jumpserver/core-ce:v3.10.10": Error response from daemon: manifest unknown
--

<br class="Apple-interchange-newline">
</body>
</html>

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
Please try again, the problem has been fixed.
