### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by zzusunwei** [jumpserver/helm-charts#161]
**JumpServer 版本(v1.5.9以下不再支持)**
4.02

**浏览器版本**

**Bug 描述**
使用 helm 部署 4.0.2 时，pod： fountain-jms-celery 和 fountain-jms-web 无法启动
报错：
  message: >-
    {"reason": "IncorrectStatus", "message": "The current status of disk:
    d-uf67torazrj5zpdovaq7 is [In_use]"}

分析问题产生原因，这三个 pod 同时使用 jms-core 启动，三个都是用 相同的 PersistentVolumeClaim 

**Bug 重现步骤(有截图更好)**
1.  
2. 
3.

**Comment by wojiushixiaobai** [comment]
`jms_core` 和 `jms_celery` 共同读写 `/opt/jumpserver/data`，`jms_web` 读 `/opt/jumpserver/data`
这并无问题，目前尚不支持块存储，需要同时读写
