### ISSUE TITLE
[Bug] values.yaml 中 externalDatabase 与 externalRedis 的配置注释写反了

### ISSUE THREAD

**Issue by dongfg** [jumpserver/helm-charts#54]
**JumpServer 版本(v1.5.9以下不再支持)**
v2.18.0

**浏览器版本**
无

**Bug 描述**

`values.yaml` 中 `externalDatabase` 与 `externalRedis` 的配置注释写反了

**Bug 重现步骤(有截图更好)**

![image](https://user-images.githubusercontent.com/5753141/150479737-ceb8ef63-c739-4a94-b2ed-aaba68c07834.png)

https://github.com/jumpserver/helm-charts/blob/e825e1cab4c02363e61cc0859dea4970343bb01f/charts/jumpserver/values.yaml#L23-L40

**Comment by wojiushixiaobai** [comment]
OK，我处理下
