### ISSUE TITLE
[Question] 使用helm安装时出现如下问题running PreBind plugin "VolumeBinding":

### ISSUE THREAD

**Issue by ivanmissu** [jumpserver/helm-charts#57]
**请描述您的问题.**
k8s version: v1.21.5
使用helm安装出现
running PreBind plugin "VolumeBinding": Operation cannot be fulfilled on persistentvolumeclaims "jumpser-0589ra-jumpserver-jms-core-data": the object has been modified; please apply your changes to the latest version and try again
然后一直等待直到超时

**Comment by wojiushixiaobai** [comment]
检查下 pvc

**Comment by ivanmissu** [comment]
> 检查下 pvc

storageclass.storage.k8s.io "jumpserver-data" not found

**Comment by ivanmissu** [comment]
> > 检查下 pvc
> 
> storageclass.storage.k8s.io "jumpserver-data" not found
