### ISSUE TITLE
[Question] 使用时需要提前手动创建pvc jumpserver-data吗

### ISSUE THREAD

**Issue by ivanmissu** [jumpserver/helm-charts#58]
**请描述您的问题.**
使用时需要提前手动创建pvc jumpserver-data吗
目前报错
storageclass.storage.k8s.io "jumpserver-data" not found

**Comment by ivanmissu** [comment]
我这边先创建了sc   jumpserver-data
![image](https://user-images.githubusercontent.com/8721615/156287274-3067ab2d-a11f-411f-afb9-61fc2874310e.png)
![image](https://user-images.githubusercontent.com/8721615/156287458-69961c22-9ef1-48da-9243-ddb148e289fc.png)
然后安装还是出现了问题
<img width="922" alt="image" src="https://user-images.githubusercontent.com/8721615/156287527-acec657a-7920-4803-a557-49f740c5cd9b.png">

@wojiushixiaobai

**Comment by wojiushixiaobai** [comment]
本地卷无法动态提供存储功能，所有PV需手动创建

**Comment by ivanmissu** [comment]
> 

必须使用nfs或者gfs之类的吗

**Comment by wojiushixiaobai** [comment]
推荐，不是必须，你可以自己修改 helm 里面的对应代码
