### ISSUE TITLE
[Question] helm repo add 報錯

### ISSUE THREAD

**Issue by liujunfei980** [jumpserver/helm-charts#66]
使用helm部署jumpserver報以下錯誤
helm repo add jumpserver https://jumpserver.github.io/helm-charts
Error: looks like "https://jumpserver.github.io/helm-charts" is not a valid chart repository or cannot be reached: Get "https://jumpserver.github.io/helm-charts/index.yaml": proxyconnect tcp: tls: first record does not look like a TLS handshake

**Comment by wojiushixiaobai** [comment]
网络问题，请自行解决下。github.io 正常情况下需要代理才能访问
