### ISSUE TITLE
[Feature] k8s離線部署jumpserver

### ISSUE THREAD

**Issue by liujunfei980** [jumpserver/helm-charts#67]
因helm需要連接外網在線部署，是否可以出一版教程實現k8s上離線部署jumpserver？

**Comment by wojiushixiaobai** [comment]
可以使用 [installer 离线包](https://community.fit2cloud.com/#/products/jumpserver/downloads)在 k8s 上面正常导入离线镜像
```bash
cd /opt
tar -xf jumpserver-offline-installer-v2.20.2-amd64-19.tar.gz
cd /opt/jumpserver-offline-installer-v2.20.2-amd64-19/scripts/images
```
如果你的 k8s 使用 docker
```bash
docker load core:v2.20.2.tar
docker load koko:v2.20.2.tar
docker load lion:v2.20.2.tar
docker load web:v2.20.2.tar
```
如果你使用 crictl
```bash
crictl load core:v2.20.2.tar
crictl load koko:v2.20.2.tar
crictl load lion:v2.20.2.tar
crictl load web:v2.20.2.tar
```
然后下载 [helm release](https://github.com/jumpserver/helm-charts/releases/download/jumpserver-2.20.2/jumpserver-2.20.2.tgz)
在 k8s 服务器解压后正常部署即可
