### ISSUE TITLE
[Feature] Ingress apiVersion变成变量

### ISSUE THREAD

**Issue by leezer3379** [jumpserver/helm-charts#72]
**请描述您的需求或者改进建议.**
发现一个问题，k8s 1.18.x不支持这个接口
![359C527EBF6B1F78C34D5C5E003F69FF](https://user-images.githubusercontent.com/37136385/165918779-b2de0b01-6901-407f-b5fd-35efd9e2bead.jpg)
执行的时候报错了，为了增加ingress需要更改远端文件吧
![3152EF8C0860AE62E24D7BD1D8FB64E6](https://user-images.githubusercontent.com/37136385/165918891-abb372d6-d28d-4fec-b15a-ea6e2a17d5fa.jpg)

**Comment by wojiushixiaobai** [comment]
要求如下：
- Kubernetes 1.20+
- Helm 3.0

也可以自己手动修改下
