### ISSUE TITLE
[Bug] helm安装不能正常部署

### ISSUE THREAD

**Issue by ivanmissu** [jumpserver/helm-charts#87]
**JumpServer 版本(v1.5.9以下不再支持)**
latest

**浏览器版本**
chrome latest

**Bug 描述**
helm安装 指定了storage-class ，但是没有自动创建storage-class, 导致helm不能正常创建， 望修复。

**Comment by wojiushixiaobai** [comment]
不会自动创建 SC，请先自行创建
